### ISSUE TITLE
Some error with hook created

### ISSUE THREAD

**Issue by demokrrat** [Yaty/vue-spotify#2]
Hello, tell me what the problem may be
`[Vue warn]: Error in created hook: "TypeError: this.spotify.client CredentialsGrant is not a function"`
Code
![spot](https://user-images.githubusercontent.com/20026934/37040574-e05552be-2162-11e8-8924-e9239fceedb9.png)

**Comment by demokrrat** [comment]
I found what might be problematic https://github.com/thelinmichael/spotify-web-api-node/issues/94.
But I'm using the npm run dev command, is not this a web server?

**Comment by Yaty** [comment]
Yup you have to fetch the credentials on your backend first. I'll update the README. Sorry for the inconvenience.

**Comment by demokrrat** [comment]
Now it remains to figure out how to make a simple backend:)
